# -*- coding: utf-8 -*-
"""Exercícios_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ktj8PoGVMIzoa7No757ffT1qcoF7cqSc

# Resolução dos Atividades Passadas em Sala de Aula :

## Exercício 1

Faça um algoritmo usando o for para mostrar os números pares e impares de 0 a 100.
"""

## Excercício 1

for n in range(101):
  if n % 2 == 0:
    print("O número ", n, "é par")
  else:
    print("O numero", n, "é impar")

"""## Exercício 2

Escreva um script que leia três números e mostre o maior e o menor deles.

"""

## Exercício 2

a = int(input("Primeiro número: "))
b = int(input("Segundo número: "))
c = int(input("Terceiro número: "))

# Achando o maior
maior = a
if b > maior:
    maior = b
if c > maior:
    maior = c

# Achando o menor
menor = a
if b < menor:
    menor = b
if c < menor:
    menor = c

print("Maior:", maior)
print("Menor:", menor)

"""##Exercício 3

Faça um algoritmo que imprima o nome digitado pelo usuário na vertical em escada.

Exemplo:

F

FU

FUL

FULA

FULAN

FULANO
"""

## Exercício 3

nome = input("Digite seu nome: ")
escada = ""

for letra in nome:
    escada = escada + letra
    print(escada)

"""## Exercício 4

A série de Fibonacci é formada pela sequência 1,1,2,3,5,8,13,21,34,55,... (o próximo termo, a partir do  terceiro  (número 2), é sempre gerado a partir do somatório dos últimos dois) . Faça um programa capaz de gerar a série até o n−ésimo termo (onde o valor n deve ser inserido pelo usuário).

"""

## Exercício 4

n = int(input("Quantos termos você quer? "))
t1 = 1
t2 = 1
print(t1)
print(t2)

for i in range(3, n + 1):
    proximo = t1 + t2
    print(proximo)
    t1 = t2
    t2 = proximo

"""## Exercício 5

Faça um programa que leia e valide as seguintes informações:
- Nome: maior que 3 caracteres;


- Idade: entre 0 e 150;


- Salário: maior que zero;

- Sexo: 'f' ou 'm';

- Estado Civil: 's', 'c', 'v', 'd';
"""

## Exercício 5

nome = input("Nome: ")
if len(nome) <= 3:
    nome = input("Muito curto, digita outro: ")

# Idade
idade = int(input("Idade: "))
if idade < 0 or idade > 150:
    idade = int(input("Idade errada, tenta de novo: "))

# Salario
sal = float(input("Salario: "))
if sal <= 0:
    sal = float(input("Tem que ser maior que 0: "))

# Sexo
sexo = input("Sexo (f/m): ")
while sexo != 'f' and sexo != 'm':
    sexo = input("Invalido! Digite f ou m: ")

# Estado Civil
civil = input("Estado Civil: ")
while civil != 's' and civil != 'c' and civil != 'v' and civil != 'd':
    civil = input("Letra errada! Digite s, c, v ou d: ")

print("Cadastro feito.")

"""## Exercício 6

Faça um programa que peça um número inteiro e determine se ele é ou não um número primo. Um número primo é aquele que é divisível somente por ele mesmo e por 1.

Dica: Utilize o operador aritmético `%`, que retorna o resto da divisão de dois números.

"""

## Exercício 6

n = int(input("Verificar se o número: "))
divisor = 2
primo = True

if n < 2:
    primo = False
else:

    while divisor * divisor <= n:
        if n % divisor == 0:
            primo = False
            divisor += 1

if primo:
    print("O número é primo")
else:
    print("Não é primo")

"""## Exercício 7

Faça um algoritmo utilizando o laço FOR que descreva o Fatorial de um número digitado pelo usuário.
"""

## Exercício 7
num = int(input("Digite um número para calcular o fatorial: "))

if num < 0:
    print("Não existe fatorial de número negativo.")
elif num == 0 or num == 1:
    print(f"O fatorial de {num} é 1.")
else:
    fatorial = 1
    for i in range(1, num + 1):
        fatorial *= i
    print(f"O fatorial de {num} é {fatorial}")

"""## Exercício 8

Dada a lista
L = [5, 7, 2, 9, 4, 1, 3]

Escreva um programa que imprima as seguintes informações:

a) tamanho da lista.

b) maior valor da lista.

c) menor valor da lista.

d) soma de todos os elementos da lista.

e) lista em ordem crescente.

f) lista em ordem decrescente.
"""

## Exercício 8

L = [5, 7, 2, 9, 4, 1, 3]

print("a) tamanho da lista:", len(L))
print("b) maior valor da lista:", max(L))
print("c) menor valor da lista:", min(L))
print("d) soma de todos os elementos da lista:", sum(L))


print("e) lista em ordem crescente:", sorted(L))
print("f) lista em ordem decrescente:", sorted(L, reverse=True))

"""## Exercício 9

Dada a tabela em anexo , crie um dicionário que a represente.
"""

## Exercício 9

tabela = {
    "Luís": [6.5, 9.0],
    "Pedro": [6.7, 7.5],
    "Alef": [5.0, 4.5],
    "Lucas": [10.0, 9.5]
}

print("Nome | Notas")
for nome, notas in tabela.items():
    print(nome, ":", notas)

"""## Exercício 10

Utilizando o laço While faça um programa que peça uma senha ao usuário, e que imprima "Acesso liberado" apenas se o usuário digitar a senha corretamente. A senha devera ser a seguinte senha númerica : "676767".
"""

## Exercício 10

senha_certa = "676767"

while True:
    senha = input("Digite a senha: ")
    if senha == senha_certa:
        print("Acesso liberado👌")
        break
    else:
        print("Senha incorreta ❌, tente novamente.")

"""## Exercício 11

Escreva um programa que peça um número de 1 a 10, e mostre a tabuada desse número.

"""

## Exercício 11

n = int(input("Tabuada do: "))

for i in range(1, 10):
    print(n, "x", i, "=", n * i)